/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PckNovoJogoVelha;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Raul Melo
 */
public class ConfigureGame extends javax.swing.JFrame {

    JButton[] buttons1 = new JButton[9];
    JButton[] buttons2 = new JButton[9];

    private int pos = 1;
    private int pos2 = 1;
    private int pass;
    private int pass2;
    private boolean what;
    URL url;
    AudioClip audio;
    ImageIcon img;
    String imgJogador1 = "/Pckimagens/corno.jpg";
    String corJogador1;
    String imgJogador2 = "/Pckimagens/corno.jpg";
    String corJogador2;
    String nomeJoga1;
    String nomeJoga2;
    int selectedColor1;
    int selectedColor2;

    //ArrayList<Jogadas> arquivoJogadas = new ArrayList<Jogadas>();
    public ConfigureGame() {
        initComponents();
        setBounds(100, 100, 600, 530); 
        setResizable(false);
        url = getClass().getResource("gamers.wav");
        audio = Applet.newAudioClip(url);
        audio.play();
        buttons1[0] = btnImagem1;
        buttons1[1] = btnImagem2;
        buttons1[2] = btnImagem3;
        buttons1[3] = btnImagem4;
        buttons1[4] = btnImagem5;
        buttons1[5] = btnImagem6;
        buttons1[6] = btnImagem7;
        buttons1[7] = btnImagem8;
        buttons1[8] = btnImagem9;
        buttons2[0] = btnImagem11;
        buttons2[1] = btnImagem22;
        buttons2[2] = btnImagem33;
        buttons2[3] = btnImagem44;
        buttons2[4] = btnImagem55;
        buttons2[5] = btnImagem66;
        buttons2[6] = btnImagem77;
        buttons2[7] = btnImagem88;
        buttons2[8] = btnImagem99;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quadro1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        corJoga1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnImagem1 = new javax.swing.JButton();
        btnImagem2 = new javax.swing.JButton();
        btnImagem3 = new javax.swing.JButton();
        btnImagem4 = new javax.swing.JButton();
        btnImagem5 = new javax.swing.JButton();
        btnImagem6 = new javax.swing.JButton();
        btnImagem7 = new javax.swing.JButton();
        btnImagem8 = new javax.swing.JButton();
        btnImagem9 = new javax.swing.JButton();
        lblImagen1 = new javax.swing.JLabel();
        Quadro2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        corJoga2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnImagem11 = new javax.swing.JButton();
        btnImagem22 = new javax.swing.JButton();
        btnImagem33 = new javax.swing.JButton();
        btnImagem44 = new javax.swing.JButton();
        btnImagem55 = new javax.swing.JButton();
        btnImagem66 = new javax.swing.JButton();
        btnImagem77 = new javax.swing.JButton();
        btnImagem88 = new javax.swing.JButton();
        btnImagem99 = new javax.swing.JButton();
        lblImagen2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(235, 236, 158));
        setMaximumSize(new java.awt.Dimension(600, 512));
        setPreferredSize(new java.awt.Dimension(600, 520));

        Quadro1.setBackground(new java.awt.Color(247, 245, 196));
        Quadro1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações do Jogador 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        jLabel1.setText("Nome do jogador 1:");

        txtNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha a cor de sua preferência:");

        corJoga1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer", "Azul", "Vermelho", "Verde" }));
        corJoga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corJoga1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Escolha seu icone:");

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(248, 211));

        btnImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/caveira.jpg"))); // NOI18N
        btnImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem1ActionPerformed(evt);
            }
        });

        btnImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/cavi.jpg"))); // NOI18N
        btnImagem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem2ActionPerformed(evt);
            }
        });

        btnImagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/pirata.jpg"))); // NOI18N
        btnImagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem3ActionPerformed(evt);
            }
        });

        btnImagem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/tchok.jpg"))); // NOI18N
        btnImagem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem4ActionPerformed(evt);
            }
        });

        btnImagem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/tanque.jpg"))); // NOI18N
        btnImagem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem5ActionPerformed(evt);
            }
        });

        btnImagem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/agui.png"))); // NOI18N
        btnImagem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem6ActionPerformed(evt);
            }
        });

        btnImagem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/corno.jpg"))); // NOI18N
        btnImagem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem7ActionPerformed(evt);
            }
        });

        btnImagem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/leao.png"))); // NOI18N
        btnImagem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem8ActionPerformed(evt);
            }
        });

        btnImagem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/music.jpg"))); // NOI18N
        btnImagem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem9ActionPerformed(evt);
            }
        });

        lblImagen1.setText("Imagem selecionada:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnImagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Quadro1Layout = new javax.swing.GroupLayout(Quadro1);
        Quadro1.setLayout(Quadro1Layout);
        Quadro1Layout.setHorizontalGroup(
            Quadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Quadro1Layout.createSequentialGroup()
                .addGroup(Quadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corJoga1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Quadro1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Quadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Quadro1Layout.setVerticalGroup(
            Quadro1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Quadro1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corJoga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, 212, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Quadro2.setBackground(new java.awt.Color(247, 245, 196));
        Quadro2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configurações do Jogador 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12))); // NOI18N

        jLabel4.setText("Nome do jogador 2:");

        txtNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Escolha a cor de sua preferência:");

        corJoga2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qualquer", "Azul", "Vermelho", "Verde" }));

        jLabel6.setText("Escolha seu icone:");

        jPanel4.setBackground(new java.awt.Color(247, 245, 196));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 200));

        btnImagem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/caveira.jpg"))); // NOI18N
        btnImagem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem11ActionPerformed(evt);
            }
        });

        btnImagem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/cavi.jpg"))); // NOI18N
        btnImagem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem22ActionPerformed(evt);
            }
        });

        btnImagem33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/pirata.jpg"))); // NOI18N
        btnImagem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem33ActionPerformed(evt);
            }
        });

        btnImagem44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/tchok.jpg"))); // NOI18N
        btnImagem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem44ActionPerformed(evt);
            }
        });

        btnImagem55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/tanque.jpg"))); // NOI18N
        btnImagem55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem55ActionPerformed(evt);
            }
        });

        btnImagem66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/agui.png"))); // NOI18N
        btnImagem66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem66ActionPerformed(evt);
            }
        });

        btnImagem77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/corno.jpg"))); // NOI18N
        btnImagem77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem77ActionPerformed(evt);
            }
        });

        btnImagem88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/leao.png"))); // NOI18N
        btnImagem88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem88ActionPerformed(evt);
            }
        });

        btnImagem99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pckimagens/music.jpg"))); // NOI18N
        btnImagem99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagem99ActionPerformed(evt);
            }
        });

        lblImagen2.setText("Imagem selecionada:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lblImagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnImagem77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnImagem44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnImagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImagem33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem33, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem44, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem55, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem66, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImagem77, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem88, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImagem99, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Quadro2Layout = new javax.swing.GroupLayout(Quadro2);
        Quadro2.setLayout(Quadro2Layout);
        Quadro2Layout.setHorizontalGroup(
            Quadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(Quadro2Layout.createSequentialGroup()
                .addGroup(Quadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(corJoga2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Quadro2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Quadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(Quadro2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Quadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Quadro2Layout.setVerticalGroup(
            Quadro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Quadro2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corJoga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Quadro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Quadro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Quadro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quadro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1ActionPerformed

    private void txtNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome2ActionPerformed

    private void btnImagem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem2ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/cavi.jpg";
        pass = pos;
        pos = 1;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Crânio");
    }//GEN-LAST:event_btnImagem2ActionPerformed

    private void btnImagem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem6ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/agui.png";
        pass = pos;
        pos = 5;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Águi");
    }//GEN-LAST:event_btnImagem6ActionPerformed

    private void btnImagem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem7ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/corno.jpg";
        pass = pos;
        pos = 6;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Boi");
    }//GEN-LAST:event_btnImagem7ActionPerformed

    private void btnImagem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem22ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/cavi.jpg";
        pass = pos2;
        pos2 = 1;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Crânio");
    }//GEN-LAST:event_btnImagem22ActionPerformed

    private void btnImagem66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem66ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/agui.png";
        pass = pos2;
        pos2 = 5;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Águia");
    }//GEN-LAST:event_btnImagem66ActionPerformed

    private void btnImagem77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem77ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/corno.jpg";
        pass = pos2;
        pos2 = 6;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Boi");
    }//GEN-LAST:event_btnImagem77ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        // buttons1[1].setIcon(new javax.swing.ImageIcon(getClass().getResource(imgJogador1)));
        nomeJoga1 = txtNome1.getText();
        nomeJoga2 = txtNome2.getText();
        System.out.println(nomeJoga1);
        System.out.println(nomeJoga2);
        corJogador1 = corJoga1.getSelectedItem().toString();
        corJogador2 = corJoga2.getSelectedItem().toString();
        if (nomeJoga1.equals(nomeJoga2)) {
            JOptionPane.showMessageDialog(null, "Erro: Nomes iguais");
            txtNome1.setText("");
            txtNome2.setText("");
        } else if (corJogador1.equals(corJogador2)) {
            JOptionPane.showMessageDialog(null, "Erro: Cores iguais");
        } else if(nomeJoga1.length()>10 || nomeJoga2.length()>10){
             JOptionPane.showMessageDialog(null, "Erro: Nome muito grande - Máximo 10 caracteres");
        } 
        else {
            this.dispose();
            audio.stop();
            TelaJogo telaJogo = new TelaJogo();
            telaJogo.setVisible(true);
            telaJogo.nomeJoga1 = nomeJoga1;
            telaJogo.nomeJoga2 = nomeJoga2;
            telaJogo.imgJogador1 = imgJogador1;
            telaJogo.imgJogador2 = imgJogador2;
            telaJogo.corJogador1 = corJogador1;//pegar nome da cor no combobox
            telaJogo.corJogador2 = corJogador2;//pegar nome da cor no combobox
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem1ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/caveira.jpg";
        pass = pos;
        pos = 0;
        what = true;
        enableButton(pos, pass, what);
        //btnImagem11.setEnabled(false);
        lblImagen1.setText("Imagem selecionada: Caveira");
    }//GEN-LAST:event_btnImagem1ActionPerformed

    private void btnImagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem3ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/pirata.jpg";
        pass = pos;
        pos = 2;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Pirata");
    }//GEN-LAST:event_btnImagem3ActionPerformed

    private void btnImagem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem4ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/tchok.jpg";
        pass = pos;
        pos = 3;
        enableButton(pos, pass, true);

        lblImagen1.setText("Imagem selecionada: Chucky");
    }//GEN-LAST:event_btnImagem4ActionPerformed

    private void btnImagem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem5ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/tanque.jpg";
        pass = pos;
        pos = 4;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Tanque");
    }//GEN-LAST:event_btnImagem5ActionPerformed

    private void btnImagem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem8ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/leao.png";
        pass = pos;
        pos = 7;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Leão da tuf");
    }//GEN-LAST:event_btnImagem8ActionPerformed

    private void btnImagem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem9ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/music.jpg";
        pass = pos;
        pos = 8;
        enableButton(pos, pass, true);
        lblImagen1.setText("Imagem selecionada: Pirado");
    }//GEN-LAST:event_btnImagem9ActionPerformed

    private void btnImagem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem11ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/caveira.jpg";
        pass = pos2;
        pos2 = 0;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Caveira");
    }//GEN-LAST:event_btnImagem11ActionPerformed

    private void btnImagem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem33ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/pirata.jpg";
        pass = pos2;
        pos2 = 2;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Pirata");
    }//GEN-LAST:event_btnImagem33ActionPerformed

    private void btnImagem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem44ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/tchok.jpg";
        pass = pos2;
        pos2 = 3;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Chucky");
    }//GEN-LAST:event_btnImagem44ActionPerformed

    private void btnImagem55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem55ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/tanque.jpg";
        pass = pos2;
        pos2 = 4;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Tanque");
    }//GEN-LAST:event_btnImagem55ActionPerformed

    private void btnImagem88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem88ActionPerformed
        // TODO add your handling code here:
        imgJogador2 = "/Pckimagens/leao.png";
        pass = pos2;
        pos2 = 7;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Leão da tuf");
    }//GEN-LAST:event_btnImagem88ActionPerformed

    private void btnImagem99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagem99ActionPerformed
        // TODO add your handling code here:
        imgJogador1 = "/Pckimagens/music.jpg";
        pass = pos2;
        pos2 = 8;
        what = false;
        enableButton(pos2, pass, what);
        lblImagen2.setText("Imagem selecionada: Pirado");
    }//GEN-LAST:event_btnImagem99ActionPerformed

    private void corJoga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corJoga1ActionPerformed
        // TODO add your handling code here:       

    }//GEN-LAST:event_corJoga1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigureGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigureGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigureGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigureGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigureGame().setVisible(true);
            }
        });
    }

    private void enableButton(int pos, int pass, boolean what) {
        if (what) {
            buttons2[pass].setEnabled(true);
            buttons2[pos].setEnabled(false);
        } else {
            buttons1[pass].setEnabled(true);
            buttons1[pos].setEnabled(false);
        }
        if (txtNome1.getText().equals(txtNome2.getText())) {
            txtNome2.setForeground(Color.red);

            if (txtNome2.isFocusCycleRoot()) {

            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Quadro1;
    private javax.swing.JPanel Quadro2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImagem1;
    private javax.swing.JButton btnImagem11;
    private javax.swing.JButton btnImagem2;
    private javax.swing.JButton btnImagem22;
    private javax.swing.JButton btnImagem3;
    private javax.swing.JButton btnImagem33;
    private javax.swing.JButton btnImagem4;
    private javax.swing.JButton btnImagem44;
    private javax.swing.JButton btnImagem5;
    private javax.swing.JButton btnImagem55;
    private javax.swing.JButton btnImagem6;
    private javax.swing.JButton btnImagem66;
    private javax.swing.JButton btnImagem7;
    private javax.swing.JButton btnImagem77;
    private javax.swing.JButton btnImagem8;
    private javax.swing.JButton btnImagem88;
    private javax.swing.JButton btnImagem9;
    private javax.swing.JButton btnImagem99;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> corJoga1;
    private javax.swing.JComboBox<String> corJoga2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblImagen2;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    // End of variables declaration//GEN-END:variables
}
